# NAME: Angela Wu,Candice Zhang
# EMAIL: angelawu.123456789@gmail.com,candicezhang1997@gmail.com
# ID: 604763501,604757623

.SILENT:

default:
	cp lab3b.py lab3b
	chmod +x lab3b lab3b.py

dist: default
	tar -czf lab3b-604763501.tar.gz lab3b.py Makefile README

clean: dist
	rm -rf lab3b lab3b-604763501.tar.gz